name: tiktok_logo
description: Tik Tok text logo.


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true


  # assets:
  #   - images/a_dot_burr.jpeg

  fonts:
    - family: Schyler
      fonts:
         - asset: assets/fonts/Poppins-Regular.ttf
         - asset: assets/fonts/PatrickHand-Regular.ttf
         - asset: assets/fonts/Poppins-Black.ttf
           weight: 900
         - asset: assets/fonts/Poppins-BlackItalic.ttf
           weight: 900
           style: italic
         - asset: assets/fonts/Poppins-Bold.ttf
           weight: 700
         - asset: assets/fonts/Poppins-BoldItalic.ttf
           weight: 700
           style: italic
         - asset: assets/fonts/Poppins-ExtraBold.ttf
           weight: 800
         - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
           weight: 800
           style: italic
         - asset: assets/fonts/Poppins-ExtraLight.ttf
           weight: 200
         - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
           weight: 200
           style: italic
         - asset: assets/fonts/Poppins-Italic.ttf
           style: italic
         - asset: assets/fonts/Poppins-Light.ttf
           weight: 300
         - asset: assets/fonts/Poppins-LightItalic.ttf
           weight: 300
           style: italic
         - asset: assets/fonts/Poppins-Medium.ttf
           weight: 500
         - asset: assets/fonts/Poppins-MediumItalic.ttf
           weight: 500
           style: italic
         - asset: assets/fonts/Poppins-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
           weight: 600
           style: italic
         - asset: assets/fonts/Poppins-Thin.ttf
           weight: 100
         - asset: assets/fonts/Poppins-ThinItalic.ttf
           weight: 100
           style: italic

